-- paulTrap.lua
-- User program for linear Paul trap RF guide + perpendicular retrapping trap.
-- Physics: RF trapping (fast adjust), Epstein drag (free molecular), gravity.

simion.workbench_program()

local D = "C:\\users\\crossover\\Documents\\Research\\Nanospheres\\SIMION\\RF Guide\\"

-- ── Physical constants ────────────────────────────────────────────────────────
local kB  = 1.38065e-23   -- J/K
local amu = 1.66054e-27   -- kg per amu

-- ── Gas: nitrogen at 1 mbar, 293 K ───────────────────────────────────────────
local T_gas = 293         -- K
local P_gas = 0.1         -- Pa  (1e-3 mbar)
local m_N2  = 28 * amu    -- kg
-- Mean molecular speed  c_bar = sqrt(8 k_B T / (pi m))
local c_bar = math.sqrt(8 * kB * T_gas / (math.pi * m_N2))  -- ~471 m/s

-- ── Particle: 166 nm silica sphere ───────────────────────────────────────────
local r_p   = 83e-9       -- m  (radius)
local rho_p = 2200        -- kg/m³  (fused silica)
local m_p   = (4/3) * math.pi * r_p^3 * rho_p  -- ~5.3e-18 kg

-- ── Epstein drag (free molecular regime, Kn >> 1) ────────────────────────────
-- F_drag = -gamma * m_p * v,  gamma = beta/m_p  [s^-1]
-- beta = (8 pi / 3) * r_p^2 * P / c_bar   [kg/s]
-- Accommodation coefficient assumed = 1 (full thermal accommodation).
local beta_drag = (8 * math.pi / 3) * r_p^2 * P_gas / c_bar
-- gamma in SIMION time units (us^-1):  gamma_us = gamma_SI * 1e-6
local gamma_drag = beta_drag / m_p * 1e-6   -- [us^-1]  (positive)

-- Scale factor: set to 0 in the workbench Variables panel to disable drag entirely
adjustable drag_scale = 1.0

-- Terminate ion when total speed falls below this value [mm/us].
-- 1e-5 mm/us = 10 mm/s = 0.01 m/s.  Set to 0 to disable.
adjustable v_stop = 1e-5

-- Trajectory recording: write one row every record_stride time steps.
-- Set to 0 to disable recording entirely.
adjustable record_stride = 20
-- Run index appended to the output filename.  Change from the Variables panel
-- to write a fresh file without editing this script.
-- Output: trajectories_<run_number>.csv in the project folder.
adjustable run_number = 1

-- ── RF defaults (overridden by voltages file at run start) ───────────────────
-- f_RF / f_RF2 and amplitudes are written by generate_voltages.py.
-- These fallback values are used only if the voltage file is missing or has no metadata.
local _rf_omega   = 2 * math.pi * 4900 * 1e-6   -- rad/us  (default 4900 Hz, main trap)
local _V0_default = 100.0                         -- V, fallback amplitude main trap

-- PLACEHOLDER: Set f_RF2 to the correct RF frequency for the perpendicular trap.
-- The value below is used only as a fallback; the real value comes from f_RF2_Hz
-- in the voltages CSV metadata comment.
local _rf_omega_2   = 2 * math.pi * 4900 * 1e-6  -- rad/us  (PLACEHOLDER — same as main trap)
local _V0_2_default = 0.0                          -- V, fallback amplitude perp trap

-- ── Voltage schedule file ────────────────────────────────────────────────────
-- DC voltages for electrodes 3, 6, 7, 8 and the RF amplitude envelope are read
-- from voltages_<voltage_file_number>.csv generated by generate_voltages.py.
-- RF electrodes (1,2,4,5) are always driven analytically.
-- Columns are matched by header name, so column order does not matter.
adjustable voltage_file_number = 1

-- ── Gravity ──────────────────────────────────────────────────────────────────
-- GEM Y increases upward (Fusion Y = height above floor), so g is in -Y.
-- g = 9.81 m/s² = 9.81e-9 mm/us²
local g_simion = 9.81e-9  -- mm/us²

-- ── Voltage schedule (populated from file) ───────────────────────────────────
-- Main trap DC: _v3=endcap_L, _v6=ring_L, _v7=ring_R, _v8=endcap_R, _v13=ring_brake
-- Perp trap DC: _v11=trapping_lens_holder, _v12=collection_lens_holder, _v_dc2=rod DC bias
-- RF envelopes: _v_rf=main trap, _v_rf2=perp trap
local _vt, _v3, _v6, _v7, _v8, _v_rf = {}, {}, {}, {}, {}, {}
local _v11, _v12, _v13, _v_rf2, _v_dc2 = {}, {}, {}, {}, {}

local function _interp(t_tbl, v_tbl, t)
  if #t_tbl == 0 then return 0.0 end
  if t <= t_tbl[1] then return v_tbl[1] end
  if t >= t_tbl[#t_tbl] then return v_tbl[#t_tbl] end
  local lo, hi = 1, #t_tbl
  while hi - lo > 1 do
    local mid = math.floor((lo + hi) / 2)
    if t_tbl[mid] <= t then lo = mid else hi = mid end
  end
  local frac = (t - t_tbl[lo]) / (t_tbl[hi] - t_tbl[lo])
  return v_tbl[lo] + frac * (v_tbl[hi] - v_tbl[lo])
end

-- ── Trajectory recording ─────────────────────────────────────────────────────
-- Positions written in Fusion world coordinates (same frame as the STL files).
-- GEM → Fusion:  X_f = X_gem - 25,  Y_f = Y_gem - 8,  Z_f = Z_gem - 132
local _traj_file  = nil
local _traj_step  = 0   -- per-ion step counter for stride

function segment.initialize_run()
  -- Clear all schedule tables so re-runs don't accumulate rows
  _vt, _v3, _v6, _v7, _v8, _v_rf = {}, {}, {}, {}, {}, {}
  _v11, _v12, _v13, _v_rf2, _v_dc2 = {}, {}, {}, {}, {}

  do
    local vpath = D .. "voltages_" .. math.floor(voltage_file_number) .. ".csv"
    local vf = io.open(vpath, "r")
    if vf then
      -- Read all leading metadata comment lines (lines starting with '#')
      -- then the CSV header line.
      local line = vf:read("*l")
      local header_line
      while line and line:sub(1, 1) == "#" do
        local freq = line:match("f_RF_Hz=([%d%.eE%+%-]+)")
        if freq then
          _rf_omega = 2 * math.pi * tonumber(freq) * 1e-6
          simion.print("RF:  f = " .. freq .. " Hz\n")
        end
        local freq2 = line:match("f_RF2_Hz=([%d%.eE%+%-]+)")
        if freq2 then
          _rf_omega_2 = 2 * math.pi * tonumber(freq2) * 1e-6
          simion.print("RF2: f = " .. freq2 .. " Hz\n")
        end
        line = vf:read("*l")
      end
      header_line = line

      -- Build column-name → index map from the CSV header
      local col_idx = {}
      if header_line then
        local i = 0
        for col in header_line:gmatch("[^,\r\n]+") do
          i = i + 1
          col_idx[col] = i
        end
      end

      -- Map column names to destination tables
      local dest = {
        ["V_endcap"]     = _v3,
        ["V_endcap_R"]   = _v8,
        ["V_ring_L"]     = _v6,
        ["V_ring_R"]     = _v7,
        ["V_ring_brake"] = _v13,
        ["V_RF"]         = _v_rf,
        ["V_RF2"]        = _v_rf2,
        ["V_DC2"]        = _v_dc2,
        ["V_trap_lens"]  = _v11,
        ["V_coll_lens"]  = _v12,
      }

      for line in vf:lines() do
        local vals = {}
        local j = 0
        for v in line:gmatch("[^,\r\n]+") do
          j = j + 1
          vals[j] = tonumber(v)
        end
        local ti = col_idx["time_us"]
        if ti and vals[ti] then
          table.insert(_vt, vals[ti])
          for col, tbl in pairs(dest) do
            local idx = col_idx[col]
            if idx and vals[idx] then table.insert(tbl, vals[idx]) end
          end
        end
      end
      vf:close()
      simion.print("Loaded " .. #_vt .. " rows from " .. vpath .. "\n")
      local function _ch(name, tbl)
        if #tbl == 0 then
          simion.print("  " .. name .. ": NOT LOADED (column missing in CSV)\n")
        else
          simion.print(string.format("  %-14s %4d rows,  t=0: %+.1f V,  t_end: %+.1f V\n",
            name .. ":", #tbl, tbl[1], tbl[#tbl]))
        end
      end
      _ch("V_endcap",     _v3)
      _ch("V_endcap_R",   _v8)
      _ch("V_ring_L",     _v6)
      _ch("V_ring_R",     _v7)
      _ch("V_ring_brake", _v13)
      _ch("V_RF",         _v_rf)
      _ch("V_RF2",        _v_rf2)
      _ch("V_DC2",        _v_dc2)
      _ch("V_trap_lens",  _v11)
      _ch("V_coll_lens",  _v12)
    else
      simion.print("WARNING: voltage file not found: " .. vpath .. "\n")
    end
  end

  if record_stride > 0 then
    local path = D .. "trajectories_" .. math.floor(run_number) .. ".csv"
    _traj_file = io.open(path, "w")
    if _traj_file then
      _traj_file:write("ion,time_us,x_mm,y_mm,z_mm\n")
    else
      simion.print("WARNING: could not open trajectory file: " .. path .. "\n")
    end
  end
end

function segment.terminate_run()
  if _traj_file then _traj_file:close(); _traj_file = nil end
end

function segment.initialize()
  _traj_step = 0
end

-- ─────────────────────────────────────────────────────────────────────────────
-- segment.fast_adjust: called each time step to set electrode voltages.
-- ─────────────────────────────────────────────────────────────────────────────
function segment.fast_adjust()
  local t   = ion_time_of_flight

  -- Main trap RF (electrodes 1, 2, 4, 5)
  local amp = #_v_rf > 0 and _interp(_vt, _v_rf, t) or _V0_default
  local V_RF = amp * math.cos(_rf_omega * t)
  adj_elect[1] =  V_RF    -- rod pair 1, left   (+RF phase)
  adj_elect[2] = -V_RF    -- rod pair 2, left   (-RF phase)
  adj_elect[4] =  V_RF    -- rod pair 1, right  (+RF phase)
  adj_elect[5] = -V_RF    -- rod pair 2, right  (-RF phase)

  -- Main trap DC (electrodes 3, 6, 7, 8)
  if #_v3  > 0 then adj_elect[3] = _interp(_vt, _v3,  t) end
  if #_v6  > 0 then adj_elect[6] = _interp(_vt, _v6,  t) end
  if #_v7  > 0 then adj_elect[7] = _interp(_vt, _v7,  t) end
  if #_v8  > 0 then adj_elect[8] = _interp(_vt, _v8,  t) end

  -- Perpendicular trap RF + DC bias (electrodes 9, 10)
  -- Pair 1: +(V_RF2·cos + V_DC2),  Pair 2: -(V_RF2·cos + V_DC2)
  -- Mathieu parameters: q = 4eV_RF2/(mω²r₀²),  a = 8eV_DC2/(mω²r₀²)
  local amp2 = #_v_rf2 > 0 and _interp(_vt, _v_rf2, t) or _V0_2_default
  local dc2  = #_v_dc2  > 0 and _interp(_vt, _v_dc2,  t) or 0.0
  local V_RF2 = amp2 * math.cos(_rf_omega_2 * t) + dc2
  adj_elect[9]  =  V_RF2   -- trap rod pair 1, TL+BR  (+RF2+DC phase)
  adj_elect[10] = -V_RF2   -- trap rod pair 2, TR+BL  (-RF2-DC phase)

  -- Perpendicular trap DC (electrodes 11, 12)
  if #_v11 > 0 then adj_elect[11] = _interp(_vt, _v11, t) end
  if #_v12 > 0 then adj_elect[12] = _interp(_vt, _v12, t) end

  -- Braking ring electrode (electrode 13)
  if #_v13 > 0 then adj_elect[13] = _interp(_vt, _v13, t) end

  -- Electrodes 14, 15 (glass lenses) are dielectric — not driven here.
end

-- ─────────────────────────────────────────────────────────────────────────────
-- segment.accel_adjust: called each time step to add non-electric accelerations.
-- ion_ax/y/z_mm already contain the electric field acceleration [mm/us²].
-- We apply Epstein drag + gravity using the finite-timestep correction from
-- SIMION's drag.lua example (avoids underestimating drag over long time steps).
-- ─────────────────────────────────────────────────────────────────────────────
function segment.terminate()
  if v_stop > 0 then
    local speed = math.sqrt(ion_vx_mm^2 + ion_vy_mm^2 + ion_vz_mm^2)
    if speed < v_stop then ion_splat = 1 end
  end
end

function segment.accel_adjust()
  if ion_time_step == 0 then return end

  local g = drag_scale * gamma_drag
  local tterm = ion_time_step * g

  if tterm < 1e-12 then
    -- No drag (or negligible): just add gravity directly
    ion_ay_mm = ion_ay_mm - g_simion
  else
    -- Finite-timestep correction factor
    local factor = (1 - math.exp(-tterm)) / tterm
    ion_ax_mm = factor * (ion_ax_mm - g * ion_vx_mm)
    ion_ay_mm = factor * (ion_ay_mm - g * ion_vy_mm - g_simion)
    ion_az_mm = factor * (ion_az_mm - g * ion_vz_mm)
  end

  -- Record trajectory (Fusion world coordinates)
  if _traj_file and record_stride > 0 then
    _traj_step = _traj_step + 1
    if _traj_step % record_stride == 0 then
      _traj_file:write(string.format("%d,%.4f,%.5f,%.5f,%.5f\n",
        ion_number,
        ion_time_of_flight,
        ion_px_mm - 25.0,
        ion_py_mm - 8.0,
        ion_pz_mm - 132.0))
    end
  end
end
